name: ecommerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    provider: ^6.0.2
    intl: ^0.17.0
    cupertino_icons: ^1.0.2
    json_annotation: ^4.4.0
    webview_flutter: ^2.8.0
    flutter_html: ^2.2.1
    http: ^0.13.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner:
    json_serializable: ^6.1.5
    flutter_lints: ^1.0.0



flutter:
    uses-material-design: true

    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    fonts:
        - family: Lato
          fonts:
              - asset: assets/fonts/Lato-Regular.ttf
              - asset: assets/fonts/Lato-Bold.ttf
                weight: 700
        - family: Anton
          fonts:
              - asset: assets/fonts/Anton-Regular.ttf
